version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "incentcard"
      POSTGRES_PASSWORD: "password"
